name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting & bye
        run: |
            echo "Hello World"
            echo "bye-bye"
